### ISSUE TITLE
ComfyUI Setup Error

### ISSUE THREAD

**Issue by architectonio** [Teachings/AIServerSetup#1]
First of all I want to thank you for the Tutorial.

After creating and enabling a Python virtual environment, when I am trying to run "docker build -t comfyui-gguf:latest ." I get the following error:
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

**Comment by mtcl** [comment]
This warning appears because the pip command is being executed as the root user within Docker build process. It's not necessarily an error, but rather a cautionary message suggesting best practices for package management. However, it does not usually prevent the build process from completing. If you see it is represented as "Warning: "

**Comment by architectonio** [comment]
> This warning appears because the pip command is being executed as the root user within Docker build process. It's not necessarily an error, but rather a cautionary message suggesting best practices for package management. However, it does not usually prevent the build process from completing. If you see it is represented as "Warning: "

Thank you

**Comment by mtcl** [comment]
You're welcome!
